### ISSUE TITLE
Add custom exception where necessary

### ISSUE THREAD

**Issue by jmulford-bandwidth** [Bandwidth/messaging-java-sdk#23]
After #12 is closed we should use this exception in the proper places

**Comment by jmulford-bandwidth** [comment]
Holding off until https://github.com/Bandwidth/messaging-java-sdk/pull/22 is finalized

**Comment by fuchsnj** [comment]
After playing around with the code for a bit, we found a good way to use the custom exceptions, and created #25 to handle this
